### ISSUE TITLE
Create GitHub Documentation

### ISSUE THREAD

**Issue by dgp1130** [uniform-team/Uniform-Validation-Language#1]
If we want to gain interest in this project then we need a GitHub page that actually looks like the repository is active and shows what the Uniform language can accomplish. We should show the language in its simplist form and an example of each major feature. We may also want to start a wiki on here with some examples and what-not.

**Comment by sawyernovak** [comment]
In progress, although the grammar has significantly changed and core design and philosophy is changing as well. Will suspend work until a clear foundation is rebuilt.

**Comment by sawyernovak** [comment]
Opening new issues that are more specific
