### ISSUE TITLE
Standardize Error Messages

### ISSUE THREAD

**Issue by dgp1130** [uniform-team/Uniform-Validation-Language#10]
Currently, error messages are fairly ad hoc and specific to the particular instance they are thrown. We should have some standarized error messages which can be used throughout to give consistent information.

Best way of doing this would probably be a new object which extends `Error` with some clearly defined messages and information.

**Comment by sawyernovak** [comment]
@dgp1130  this issue might be closed already? We added the whole error class so this should be fine I think. Close it yourself if you aggree.

**Comment by dgp1130** [comment]
Yeah, this is mostly taken care of already.
