### ISSUE TITLE
Reimplement Lexer

### ISSUE THREAD

**Issue by dgp1130** [uniform-team/Uniform-Validation-Language#22]
Since we have decided to reimplement the language from scratch, the obvious place to start is the lexer. There aren't many improvements required here, the only significant one is to make it more functional. The lexer should take an input file and return a function which gets the next token each time it is called.

```
var tokenize = tokenizer("@var: true;");
tokenize(); // @var
tokenize(); // :
tokenize(); // true
tokenize(); // ;
tokenize(); // EOF
```

**Comment by sawyernovak** [comment]
Reviewed. Code looks good although missing a couple test cases imo. I will add them and close the ticket.
