### ISSUE TITLE
Reimplement Parser

### ISSUE THREAD

**Issue by dgp1130** [uniform-team/Uniform-Validation-Language#23]
The parser needs to be reimplemented with the new changes to the language. There wasn't anything in particular wrong with the old implementation, however the grammar has changed significantly and all the components `parser` uses (such as `evaluator`, `listeners`, etc.) are currently missing. Not to mention the interface changes to `lexer`.

**Comment by sawyernovak** [comment]
Reviewed. Code looks fine although we are probably missing some test cases. Be sure to update when we add in things like arrays but I think this is a good enough to close the "reimplement" goal of this ticket.
