### ISSUE TITLE
Upgrade to ES6

### ISSUE THREAD

**Issue by dgp1130** [uniform-team/Uniform-Validation-Language#24]
The language redesign and reimplementation is a good opportunity to upgrade the source code to use ES6. We can't expect browser support for it, but we can use Babel to compile to ES5 code which is supported. The only major downside is adding a compilation step, but we already use Browserify anyways, so there's not really an extra step. This would also be a good time to remove Grunt, as it is overcomplicating a build process which is mostly managed by WebStorm.

**Comment by sawyernovak** [comment]
I don't know enough about es6 to fully understand this. Although the changes you made looks fine and it works. So it works...???
