### ISSUE TITLE
Update Home Page

### ISSUE THREAD

**Issue by sawyernovak** [uniform-team/Uniform-Validation-Language#37]
Home page code is outdated. It also needs a grammar check and restructure.

**Comment by sawyernovak** [comment]
Renamed to "Uniform Introduction" on the wiki page.

I'm a little unsure about the new notation again. I'll try talk with you tomorrow? to get my settled to the new stuff. I'd like for you to look through the code and see if I am using it right.

@dgp1130

**Comment by sawyernovak** [comment]
Just kidding, needs to be home otherwise it won't start on that page.

**Comment by dgp1130** [comment]
A made minor edits throughout just to improve the readability, nothing very special there.

A few more significant comments:
* The initial "What is Uniform?" section's rhetorical questions don't really mean a whole lot to me reading through them. I think they should focus on the specific pain points Uniform addresses.
    * Have you tried to implement simple form logic but find yourself with a mess of unmaintainable code?
    * Do you find yourself fighting the JavaScript language, rather than working with it?
    * Do you hate writing your form validation once on the client, and again on the server?
* I moved the description of the form's logic into the Uniform section, so it could display the HTML and get the structure out of the way before we discuss the validation logic.
* I added more comments to the Uniform code to be more explicit and made a few corrections.
    * The checkbox's name was inconsistent between the Uniform and HTML, I used `checkCar` to reinforce that it is a checkbox.
    * `make model year { }` should probably be `make, model, year { }`. I say "probably" because that functionality doesn't exist yet. I don't know if we should use three blocks for it just so it actually runs in the current build.
    * Added a section telling users that it will automatically submit the form for them without any JavaScript.
    * Updated the JavaScript hooks. `$("#sel").ufm()` doesn't exist anymore. We may want to add that back and some point, but currently you can only access the root tag via JavaScript. `$("[name=\"subForm\"]")` especially doesn't work because there is no HTML element `<input name="subForm" />`, so we would probably need to leverage the `selector` tag to make that work.

**Comment by sawyernovak** [comment]
This page is fine for now. I'm going to close it. We can update it later.
